version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      # инициализация схемы и данных
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      # URL для SQLAlchemy
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
