version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8501:8501"
    # переопределяем команду на запуск streamlit
    command: >
      streamlit run app/frontend.py
      --server.port 8501
      --server.address 0.0.0.0
    # указываем URL API, чтобы фронтенд знал, куда слать запросы
    environment:
      API_URL: http://api:8000
